name: Build & Deploy on S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: mvn clean package

      - name: Sync templates to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          source-dir: src/main/resources/templates/
          bucket: my-springbottt-bucket
          region: us-north-1
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
